"""add AI persistence tables

Revision ID: af588838f85e
Revises: 97f323d7f27c
Create Date: 2026-07-30 14:39:31.052323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af588838f85e'
down_revision: Union[str, Sequence[str], None] = '97f323d7f27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_FOR_APPROVAL', 'COMPLETED', 'FAILED', name='aiconversationstatus'), nullable=False),
    sa.Column('current_intent', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_thread_id'), ['thread_id'], unique=True)

    op.create_table('ai_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.Enum('MODEL_REQUEST', 'MODEL_RESPONSE', 'TOOL_CALL', 'TOOL_RESULT', 'STATE_CHANGE', 'HUMAN_APPROVAL_REQUESTED', 'HUMAN_APPROVED', 'HUMAN_REJECTED', 'ERROR', name='aieventtype'), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_events_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_events_request_id'), ['request_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', 'TOOL', name='aimessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_role'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('ai_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_ai_events_id'))
        batch_op.drop_index(batch_op.f('ix_ai_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_ai_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_events_conversation_id'))

    op.drop_table('ai_events')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_thread_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_customer_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
